import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillInstagram, AiFillLinkedin, AiFillGithub} from 'react-icons/ai';
import Image from 'next/image';
import dan from '../public/ddl.jpg'
import por from '../public/porfolio.png'
 

export default function Home() {
  return (
    <>
      <Head>
        <title>Danyal Nemati Portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-black px-10'>   
        <section className='min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
          <h1 className='text-xl font-style: italic'>Welcome!</h1>
          <ul className='flex items-center'>
            <li><BsFillMoonStarsFill className='cursor-pointer text-2xl'/></li>

            <li> <a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-black px-4 py-2 rounded-md ml-8' href="https://docs.google.com/document/d/1A0ngs8pP13IeRRM7HfhgE4qvP8k8EX_fRBcWtEogEtQ/edit"> Resume</a></li>
          </ul>
          </nav>
          <div className='text-center p-10'>
            <h2 className='text-4xl py-2 text-green-600 font-medium'>Danyal Nemati</h2>
            <h3 className='text-2xl'>Web Develper</h3>
            <p className='text-md py-5 leading-8 text-white'>3rd year Computer Science Major at California State 
              University Fullerton, who enjoys making Websites using JavaScript.
            </p>
          </div>
          <div className='text-4xl flex justify-center gap-16 py-4'>
            <a href='https://github.com/danyalnemati8'><AiFillGithub/></a>
            <a href='https://www.linkedin.com/in/danyal-nemati-01b673221/'><AiFillLinkedin/></a>
            <a href='https://www.instagram.com/iron.hashira/'><AiFillInstagram/></a>
          </div>
          <div className='relative mx-auto rounded-full w-80 h-80 mt-20 overflow-hidden'>
            <Image src={dan} alt={''}/>
          </div>
        </section>
        <section>
          <div>
            <h3 className='text-3xl py-1'>About Me</h3>
            <p className='text-md py-2 leading-8'>
              Team oriented programmer, who loves working with others in order to 
              come up with something special. On my free time I love to powerlift,
               I am a one time State Champ! I Also enjoy spending time with my family.
            </p>
            <h4 className='text-3xl py-1'> Programming Languages :</h4>
            <ul className=' list-outside list-disc ml-6 py-2'>
            <li>React: JSX, TSX, JS, TS, HTML, CSS</li>
            <li>C++, C, Java, Python</li>
            <li>APIs, PHP, MYSQL </li>
            </ul>
            <div>
              <Image src={por} width={100} height={100} alt={''}/>
              <h3>Personal Website</h3>
              <p>
                Used TypeScript as well as Tailwind in React in order to
                make this Web Page.
              </p>
              
            </div>
          </div>
        </section>
      </main>
    </>
  )
}
